version: 2
jobs:  
  build:  
    docker:  
      - image: circleci/node:lts
    steps:
      - checkout
      - run: 
          name: Build
          command: npm ci
      - run:
          name: Test
          command: npm run test
      - run:
          name: Deploy
          command: npm run start &